In [3]:
import pandas as pd
import numpy as np

In [4]:
try:
    books=pd.read_csv(r'BX-Books.csv',sep=";",on_bad_lines='skip',encoding='latin-1',dtype={3: str})


except Exception as e:
    print("File not found ")
    print(e)

In [5]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
books.iloc[50]['Image-URL-S']

'http://images.amazon.com/images/P/0812523873.01.THUMBZZZ.jpg'

In [7]:
books.loc[1:4,'Book-Title':'Book-Author'	]

                                          Book-Title           Book-Author
1                                       Clara Callan  Richard Bruce Wright
2                               Decision in Normandy          Carlo D'Este
3  Flu: The Story of the Great Influenza Pandemic...      Gina Bari Kolata
4                             The Mummies of Urumchi       E. J. W. Barber

In [8]:
books.iloc[5:10,0:5]

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner

In [9]:
books.info()

<class 'pandas.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  str
 1   Book-Title           271360 non-null  str
 2   Book-Author          271358 non-null  str
 3   Year-Of-Publication  271360 non-null  str
 4   Publisher            271358 non-null  str
 5   Image-URL-S          271360 non-null  str
 6   Image-URL-M          271360 non-null  str
 7   Image-URL-L          271357 non-null  str
dtypes: str(8)
memory usage: 84.4 MB

In [10]:
books.describe()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
count,271360,271360,271358,271360,271358,271360,271360,271357
unique,271360,242135,102022,118,16807,271044,271044,271041
top,0195153448,Selected Poems,Agatha Christie,2002,Harlequin,http://images.amazon.com/images/P/042511774X.0...,http://images.amazon.com/images/P/042511774X.0...,http://images.amazon.com/images/P/042511774X.0...
freq,1,27,632,17627,7535,2,2,2

In [11]:
books.shape

(271360, 8)

In [12]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='str')

In [13]:
books=books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher','Image-URL-L']]

In [14]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [15]:
# Rename book title 
books.rename(columns={"Book-Title":'Title',"Book-Author	":'Author',"Year-Of-Publication":'Year',"Publisher":'Publisher',"Image-URL-L":'Image_Url'},inplace=True)

In [16]:
books.head()

,ISBN,Title,Book-Author,Year,Publisher,Image_Url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [17]:
# Now the load the second dataset 
try:
    Users=pd.read_csv(r"BX-Users.csv",sep=";",on_bad_lines='skip',encoding='latin-1')
except Exception as e:
    print("File not found")
    print(e)

In [18]:
Users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [19]:
Users.shape

(278858, 3)

In [20]:
# Lets rename columns name

Users.rename(columns={"User-ID	":'user_id',"Location":'location',"Age":'age'},inplace=True)

In [21]:
Users.head()

   User-ID                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [22]:
rating=pd.read_csv(r"BX-Book-Ratings.csv",sep=";",on_bad_lines='skip',encoding='latin-1')

In [23]:
rating.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [24]:
Users.shape

(278858, 3)

In [25]:
print(books.shape,Users.shape,rating.shape,sep="\n")

(271360, 6)
(278858, 3)
(1149780, 3)

In [26]:
rating['User-ID'].value_counts()

User-ID
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

In [27]:
# letas store users who had at least rated more than 200 books 
x=rating['User-ID'].value_counts()>200

In [28]:
x

User-ID
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
276697    False
276706    False
276709    False
276721    False
276723    False
Name: count, Length: 105283, dtype: bool

In [29]:
x[x].shape

(899,)

In [30]:
y=x[x].index

In [31]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,   9856,  28634,  44296,  59727,  73681, 155916, 188951, 268622,
       274808],
      dtype='int64', name='User-ID', length=899)

In [32]:
rating=rating[rating['User-ID'].isin(y)]

In [33]:
rating.head()

      User-ID        ISBN  Book-Rating
1456   277427  002542730X           10
1457   277427  0026217457            0
1458   277427  003008685X            8
1459   277427  0030615321            0
1460   277427  0060002050            0

In [34]:
# Now join rating with books
rating_with_books=rating.merge(books,on='ISBN')

In [35]:
rating_with_books.head()

,User-ID,ISBN,Book-Rating,Title,Book-Author,Year,Publisher,Image_Url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...

In [36]:
number_rating=rating_with_books.groupby('Title')['Book-Rating'].count().reset_index()

In [37]:
number_rating.head()

                                               Title  Book-Rating
0   A Light in the Storm: The Civil War Diary of ...            2
1                              Always Have Popsicles            1
2               Apple Magic (The Collector's series)            1
3   Beyond IBM: Leadership Marketing and Finance ...            1
4   Clifford Visita El Hospital (Clifford El Gran...            1

In [38]:
number_rating.rename(columns={"Book-Rating":'num_of_rating'},inplace=True)

In [39]:
number_rating.rename(columns={"num_rating":'num_of_rating'},inplace=True)

In [40]:
number_rating.head()

                                               Title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [41]:
final_rating=rating_with_books.merge(number_rating,on='Title')

In [42]:
final_rating.head()

,User-ID,ISBN,Book-Rating,Title,Book-Author,Year,Publisher,Image_Url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,7
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,1
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,1
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,13

In [43]:
# letas take those books which got at least 50 rating of users
final_rating=final_rating[final_rating['num_of_rating']>=50]

In [44]:
final_rating.head()

,User-ID,ISBN,Book-Rating,Title,Book-Author,Year,Publisher,Image_Url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [45]:
final_rating.shape

(61853, 9)

In [46]:
final_rating.drop_duplicates(['User-ID','Title'],inplace=True)

In [47]:
final_rating.head()

,User-ID,ISBN,Book-Rating,Title,Book-Author,Year,Publisher,Image_Url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [48]:
final_rating.shape

(59850, 9)

In [49]:
final_rating.isnull().sum()

User-ID          0
ISBN             0
Book-Rating      0
Title            0
Book-Author      0
Year             0
Publisher        0
Image_Url        0
num_of_rating    0
dtype: int64

In [50]:
# Lets create a pivot table 


book_pivot=final_rating.pivot_table(columns='User-ID',index='Title',values='Book-Rating')

In [51]:
book_pivot.head()

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN

In [52]:
book_pivot.fillna(0,inplace=True)

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [53]:
book_pivot.head()

User-ID,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0

In [54]:
from scipy.sparse import csr_matrix

In [55]:
book_sparse=csr_matrix(book_pivot)

In [56]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [58]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')

In [59]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [60]:
book_pivot.iloc[237,:]

User-ID
254       9.0
2276      0.0
2766      0.0
2977      0.0
3363      0.0
         ...
275970    9.0
277427    0.0
277478    0.0
277639    0.0
278418    0.0
Name: Harry Potter and the Chamber of Secrets (Book 2), Length: 888, dtype: float64

In [61]:
distance,suggestion=model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [62]:
distance

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [63]:
suggestion

array([[237, 238, 240, 241, 184, 536]])

In [64]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='str', name='Title')

In [65]:
# Keeps book name 
book_name=book_pivot.index

In [66]:
book_name

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='str', name='Title', length=742)

In [74]:
book_name[642]

'The Secret Garden'

In [70]:
final_rating.head()

,User-ID,ISBN,Book-Rating,Title,Book-Author,Year,Publisher,Image_Url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
13,277427,0060930535,0,The Poisonwood Bible: A Novel,Barbara Kingsolver,1999,Perennial,http://images.amazon.com/images/P/0060930535.0...,133
15,277427,0060934417,0,Bel Canto: A Novel,Ann Patchett,2002,Perennial,http://images.amazon.com/images/P/0060934417.0...,108
18,277427,0061009059,9,One for the Money (Stephanie Plum Novels (Pape...,Janet Evanovich,1995,HarperTorch,http://images.amazon.com/images/P/0061009059.0...,108
24,277427,006440188X,0,The Secret Garden,Frances Hodgson Burnett,1998,HarperTrophy,http://images.amazon.com/images/P/006440188X.0...,79

In [73]:
np.where(book_pivot.index=='The Secret Garden')[0][0]

np.int64(642)

In [76]:
# Final _rating ['Title].value_counts()
ids=np.where(final_rating['Title']=="Harry Potter and the Chamber of Secrets (Book 2)")[0][0]

In [77]:
final_rating.iloc[ids]['Image_Url']

'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg'

In [78]:
book_name=[book_name.append(book_pivot.index)for book_id in suggestion]

In [79]:
book_name

[Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
        '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
        'A Child Called \It\": One Child's Courage to Survive"',
        'A Civil Action', 'A Cry In The Night',
        ...
        'Winter Solstice', 'Wish You Well', 'Without Remorse',
        'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
        'Year of Wonders', 'You Belong To Me',
        'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
        'Zoya', '\O\" Is for Outlaw"'],
       dtype='str', name='Title', length=1484)]

In [80]:
ids_index=[]
for name in book_name[0]:
    ids=np.where(final_rating['Title']==name)[0][0]
    ids_index.append(ids)

In [ ]:
# List comp
# ids_index = [np.where(final_rating['Title'] == name)[0][0] for name in book_name[0]]

In [81]:
ids_index

[np.int64(332),
 np.int64(842),
 np.int64(134),
 np.int64(711),
 np.int64(956),
 np.int64(327),
 np.int64(249),
 np.int64(1381),
 np.int64(521),
 np.int64(281),
 np.int64(787),
 np.int64(1577),
 np.int64(1102),
 np.int64(2463),
 np.int64(171),
 np.int64(418),
 np.int64(169),
 np.int64(444),
 np.int64(168),
 np.int64(1017),
 np.int64(182),
 np.int64(93),
 np.int64(20),
 np.int64(792),
 np.int64(105),
 np.int64(126),
 np.int64(1829),
 np.int64(231),
 np.int64(551),
 np.int64(410),
 np.int64(210),
 np.int64(85),
 np.int64(348),
 np.int64(497),
 np.int64(618),
 np.int64(1319),
 np.int64(193),
 np.int64(1138),
 np.int64(1923),
 np.int64(135),
 np.int64(798),
 np.int64(106),
 np.int64(114),
 np.int64(26),
 np.int64(736),
 np.int64(222),
 np.int64(175),
 np.int64(4325),
 np.int64(87),
 np.int64(579),
 np.int64(426),
 np.int64(1578),
 np.int64(459),
 np.int64(1796),
 np.int64(333),
 np.int64(1786),
 np.int64(1339),
 np.int64(1338),
 np.int64(1431),
 np.int64(112),
 np.int64(107),
 np.int64(148),
 np.int64(1018),
 np.int64(74),
 np.int64(1184),
 np.int64(1532),
 np.int64(183),
 np.int64(1055),
 np.int64(532),
 np.int64(893),
 np.int64(2513),
 np.int64(2),
 np.int64(154),
 np.int64(252),
 np.int64(1852),
 np.int64(476),
 np.int64(827),
 np.int64(199),
 np.int64(2095),
 np.int64(3084),
 np.int64(2638),
 np.int64(1588),
 np.int64(43),
 np.int64(1154),
 np.int64(1140),
 np.int64(554),
 np.int64(57),
 np.int64(1026),
 np.int64(659),
 np.int64(516),
 np.int64(540),
 np.int64(435),
 np.int64(197),
 np.int64(1211),
 np.int64(574),
 np.int64(294),
 np.int64(295),
 np.int64(80),
 np.int64(75),
 np.int64(715),
 np.int64(291),
 np.int64(2472),
 np.int64(257),
 np.int64(1695),
 np.int64(2371),
 np.int64(236),
 np.int64(41),
 np.int64(42),
 np.int64(146),
 np.int64(561),
 np.int64(533),
 np.int64(534),
 np.int64(7),
 np.int64(1141),
 np.int64(1294),
 np.int64(237),
 np.int64(100),
 np.int64(323),
 np.int64(1288),
 np.int64(615),
 np.int64(996),
 np.int64(1423),
 np.int64(1975),
 np.int64(151),
 np.int64(484),
 np.int64(458),
 np.int64(392),
 np.int64(1789),
 np.int64(40),
 np.int64(313),
 np.int64(260),
 np.int64(368),
 np.int64(873),
 np.int64(660),
 np.int64(2475),
 np.int64(1634),
 np.int64(71),
 np.int64(206),
 np.int64(286),
 np.int64(503),
 np.int64(258),
 np.int64(1474),
 np.int64(290),
 np.int64(3664),
 np.int64(1573),
 np.int64(117),
 np.int64(278),
 np.int64(2616),
 np.int64(796),
 np.int64(2268),
 np.int64(2526),
 np.int64(2583),
 np.int64(159),
 np.int64(2514),
 np.int64(1640),
 np.int64(1036),
 np.int64(238),
 np.int64(1586),
 np.int64(116),
 np.int64(454),
 np.int64(66),
 np.int64(288),
 np.int64(524),
 np.int64(174),
 np.int64(185),
 np.int64(1418),
 np.int64(1530),
 np.int64(285),
 np.int64(434),
 np.int64(2105),
 np.int64(2922),
 np.int64(700),
 np.int64(378),
 np.int64(716),
 np.int64(73),
 np.int64(1594),
 np.int64(903),
 np.int64(170),
 np.int64(481),
 np.int64(754),
 np.int64(2115),
 np.int64(1157),
 np.int64(889),
 np.int64(852),
 np.int64(786),
 np.int64(196),
 np.int64(1600),
 np.int64(801),
 np.int64(265),
 np.int64(731),
 np.int64(336),
 np.int64(536),
 np.int64(1455),
 np.int64(1090),
 np.int64(571),
 np.int64(269),
 np.int64(201),
 np.int64(624),
 np.int64(978),
 np.int64(138),
 np.int64(191),
 np.int64(678),
 np.int64(108),
 np.int64(1067),
 np.int64(1150),
 np.int64(1108),
 np.int64(213),
 np.int64(384),
 np.int64(84),
 np.int64(2517),
 np.int64(1249),
 np.int64(882),
 np.int64(157),
 np.int64(917),
 np.int64(137),
 np.int64(817),
 np.int64(460),
 np.int64(39),
 np.int64(1178),
 np.int64(642),
 np.int64(10),
 np.int64(1328),
 np.int64(277),
 np.int64(246),
 np.int64(6),
 np.int64(334),
 np.int64(610),
 np.int64(324),
 np.int64(522),
 np.int64(988),
 np.int64(1860),
 np.int64(50),
 np.int64(2760),
 np.int64(1903),
 np.int64(1329),
 np.int64(500),
 np.int64(969),
 np.int64(44),
 np.int64(321),
 np.int64(322),
 np.int64(45),
 np.int64(46),
 np.int64(573),
 np.int64(2536),
 np.int64(2439),
 np.int64(127),
 np.int64(2527),
 np.int64(273),
 np.int64(1369),
 np.int64(68),
 np.int64(69),
 np.int64(1739),
 np.int64(58),
 np.int64(142),
 np.int64(619),
 np.int64(818),
 np.int64(694),
 np.int64(707),
 np.int64(2435),
 np.int64(124),
 np.int64(819),
 np.int64(307),
 np.int64(1054),
 np.int64(620),
 np.int64(472),
 np.int64(1238),
 np.int64(1882),
 np.int64(593),
 np.int64(1953),
 np.int64(261),
 np.int64(111),
 np.int64(160),
 np.int64(809),
 np.int64(89),
 np.int64(283),
 np.int64(1475),
 np.int64(1092),
 np.int64(2434),
 np.int64(250),
 np.int64(393),
 np.int64(469),
 np.int64(181),
 np.int64(29),
 np.int64(194),
 np.int64(166),
 np.int64(361),
 np.int64(1630),
 np.int64(747),
 np.int64(396),
 np.int64(63),
 np.int64(59),
 np.int64(866),
 np.int64(523),
 np.int64(575),
 np.int64(729),
 np.int64(254),
 np.int64(2174),
 np.int64(433),
 np.int64(64),
 np.int64(2305),
 np.int64(2445),
 np.int64(2444),
 np.int64(2446),
 np.int64(1127),
 np.int64(785),
 np.int64(705),
 np.int64(1053),
 np.int64(270),
 np.int64(1231),
 np.int64(665),
 np.int64(482),
 np.int64(2352),
 np.int64(2607),
 np.int64(2537),
 np.int64(544),
 np.int64(35),
 np.int64(314),
 np.int64(1278),
 np.int64(179),
 np.int64(456),
 np.int64(76),
 np.int64(32),
 np.int64(806),
 np.int64(279),
 np.int64(11),
 np.int64(425),
 np.int64(2390),
 np.int64(2118),
 np.int64(2119),
 np.int64(234),
 np.int64(149),
 np.int64(17),
 np.int64(145),
 np.int64(144),
 np.int64(1615),
 np.int64(228),
 np.int64(24),
 np.int64(187),
 np.int64(2248),
 np.int64(86),
 np.int64(381),
 np.int64(480),
 np.int64(38),
 np.int64(215),
 np.int64(65),
 np.int64(850),
 np.int64(1823),
 np.int64(2431),
 np.int64(1052),
 np.int64(280),
 np.int64(757),
 np.int64(34),
 np.int64(1610),
 np.int64(581),
 np.int64(2229),
 np.int64(272),
 np.int64(120),
 np.int64(1050),
 np.int64(18),
 np.int64(245),
 np.int64(693),
 np.int64(325),
 np.int64(311),
 np.int64(382),
 np.int64(529),
 np.int64(263),
 np.int64(99),
 np.int64(266),
 np.int64(274),
 np.int64(1169),
 np.int64(1159),
 np.int64(177),
 np.int64(22),
 np.int64(1088),
 np.int64(2334),
 np.int64(2529),
 np.int64(1187),
 np.int64(78),
 np.int64(560),
 np.int64(981),
 np.int64(3),
 np.int64(30),
 np.int64(840),
 np.int64(239),
 np.int64(1749),
 np.int64(1056),
 np.int64(2256),
 np.int64(90),
 np.int64(584),
 np.int64(136),
 np.int64(1667),
 np.int64(860),
 np.int64(479),
 np.int64(784),
 np.int64(2369),
 np.int64(101),
 np.int64(0),
 np.int64(762),
 np.int64(2291),
 np.int64(345),
 np.int64(25),
 np.int64(2230),
 np.int64(56),
 np.int64(3445),
 np.int64(1332),
 np.int64(230),
 np.int64(720),
 np.int64(858),
 np.int64(1965),
 np.int64(200),
 np.int64(839),
 np.int64(923),
 np.int64(119),
 np.int64(577),
 np.int64(79),
 np.int64(1270),
 np.int64(205),
 np.int64(2254),
 np.int64(1203),
 np.int64(2240),
 np.int64(158),
 np.int64(335),
 np.int64(255),
 np.int64(550),
 np.int64(2705),
 np.int64(366),
 np.int64(37),
 np.int64(419),
 np.int64(580),
 np.int64(339),
 np.int64(92),
 np.int64(897),
 np.int64(61),
 np.int64(921),
 np.int64(221),
 np.int64(849),
 np.int64(1121),
 np.int64(2432),
 np.int64(655),
 np.int64(415),
 np.int64(2171),
 np.int64(1098),
 np.int64(48),
 np.int64(109),
 np.int64(875),
 np.int64(1535),
 np.int64(641),
 np.int64(121),
 np.int64(1669),
 np.int64(1666),
 np.int64(110),
 np.int64(343),
 np.int64(1297),
 np.int64(485),
 np.int64(892),
 np.int64(701),
 np.int64(1243),
 np.int64(21),
 np.int64(837),
 np.int64(1636),
 np.int64(357),
 np.int64(635),
 np.int64(1673),
 np.int64(164),
 np.int64(229),
 np.int64(1144),
 np.int64(931),
 np.int64(130),
 np.int64(346),
 np.int64(282),
 np.int64(568),
 np.int64(147),
 np.int64(1510),
 np.int64(360),
 np.int64(1654),
 np.int64(232),
 np.int64(2121),
 np.int64(3963),
 np.int64(438),
 np.int64(400),
 np.int64(383),
 np.int64(195),
 np.int64(2116),
 np.int64(216),
 np.int64(843),
 np.int64(306),
 np.int64(409),
 np.int64(2091),
 np.int64(217),
 np.int64(95),
 np.int64(256),
 np.int64(1457),
 np.int64(2373),
 np.int64(54),
 np.int64(518),
 np.int64(1736),
 np.int64(317),
 np.int64(293),
 np.int64(508),
 np.int64(77),
 np.int64(599),
 np.int64(308),
 np.int64(1658),
 np.int64(654),
 np.int64(355),
 np.int64(1473),
 np.int64(630),
 np.int64(1848),
 np.int64(1043),
 np.int64(538),
 np.int64(668),
 np.int64(1355),
 np.int64(553),
 np.int64(192),
 np.int64(315),
 np.int64(572),
 np.int64(176),
 np.int64(712),
 np.int64(376),
 np.int64(377),
 np.int64(451),
 np.int64(218),
 np.int64(225),
 np.int64(912),
 np.int64(36),
 np.int64(2317),
 np.int64(301),
 np.int64(1039),
 np.int64(211),
 np.int64(305),
 np.int64(337),
 np.int64(128),
 np.int64(267),
 np.int64(276),
 np.int64(429),
 np.int64(403),
 np.int64(2297),
 np.int64(636),
 np.int64(31),
 np.int64(331),
 np.int64(241),
 np.int64(251),
 np.int64(673),
 np.int64(744),
 np.int64(453),
 np.int64(12),
 np.int64(248),
 np.int64(1635),
 np.int64(67),
 np.int64(352),
 np.int64(2524),
 np.int64(737),
 np.int64(2004),
 np.int64(2483),
 np.int64(341),
 np.int64(207),
 np.int64(1875),
 np.int64(271),
 np.int64(113),
 np.int64(1721),
 np.int64(223),
 np.int64(165),
 np.int64(2175),
 np.int64(362),
 np.int64(2534),
 np.int64(463),
 np.int64(405),
 np.int64(406),
 np.int64(83),
 np.int64(309),
 np.int64(2565),
 np.int64(848),
 np.int64(719),
 np.int64(1158),
 np.int64(243),
 np.int64(370),
 np.int64(380),
 np.int64(19),
 np.int64(510),
 np.int64(131),
 np.int64(669),
 np.int64(598),
 np.int64(299),
 np.int64(1343),
 np.int64(750),
 np.int64(188),
 np.int64(1004),
 np.int64(15),
 np.int64(350),
 np.int64(2489),
 np.int64(365),
 np.int64(219),
 np.int64(91),
 np.int64(780),
 np.int64(987),
 np.int64(1194),
 np.int64(150),
 np.int64(407),
 np.int64(1421),
 np.int64(1382),
 np.int64(652),
 np.int64(1361),
 np.int64(16),
 np.int64(303),
 np.int64(710),
 np.int64(2518),
 np.int64(1656),
 np.int64(23),
 np.int64(464),
 np.int64(2485),
 np.int64(96),
 np.int64(227),
 np.int64(851),
 np.int64(52),
 np.int64(129),
 np.int64(629),
 np.int64(184),
 np.int64(2402),
 np.int64(983),
 np.int64(2471),
 np.int64(452),
 np.int64(1),
 np.int64(70),
 np.int64(155),
 np.int64(47),
 np.int64(565),
 np.int64(97),
 np.int64(27),
 np.int64(1415),
 np.int64(557),
 np.int64(597),
 np.int64(253),
 np.int64(259),
 np.int64(631),
 np.int64(702),
 np.int64(214),
 np.int64(2223),
 np.int64(445),
 np.int64(363),
 np.int64(88),
 np.int64(865),
 np.int64(2490),
 np.int64(4),
 np.int64(8),
 np.int64(2586),
 np.int64(349),
 np.int64(2374),
 np.int64(692),
 np.int64(1394),
 np.int64(53),
 np.int64(310),
 np.int64(122),
 np.int64(1189),
 np.int64(55),
 np.int64(829),
 np.int64(81),
 np.int64(2354),
 np.int64(162),
 np.int64(491),
 np.int64(5),
 np.int64(1916),
 np.int64(1946),
 np.int64(103),
 np.int64(173),
 np.int64(242),
 np.int64(342),
 np.int64(2478),
 np.int64(338),
 np.int64(153),
 np.int64(2244),
 np.int64(607),
 np.int64(667),
 np.int64(881),
 np.int64(1522),
 np.int64(161),
 np.int64(224),
 np.int64(1198),
 np.int64(329),
 np.int64(2249),
 np.int64(831),
 np.int64(9),
 np.int64(474),
 np.int64(1926),
 np.int64(2570),
 np.int64(220),
 np.int64(970),
 np.int64(123),
 np.int64(379),
 np.int64(721),
 np.int64(2280),
 np.int64(528),
 np.int64(2114),
 np.int64(28),
 np.int64(190),
 np.int64(82),
 np.int64(936),
 np.int64(777),
 np.int64(60),
 np.int64(51),
 np.int64(2236),
 np.int64(558),
 np.int64(62),
 np.int64(1661),
 np.int64(475),
 np.int64(2318),
 np.int64(1357),
 np.int64(275),
 np.int64(49),
 np.int64(33),
 np.int64(450),
 np.int64(172),
 np.int64(570),
 np.int64(143),
 np.int64(1855),
 np.int64(152),
 np.int64(526),
 np.int64(888),
 np.int64(530),
 np.int64(104),
 np.int64(233),
 np.int64(72),
 np.int64(98),
 np.int64(520),
 np.int64(118),
 np.int64(1517),
 np.int64(14),
 np.int64(13),
 np.int64(998),
 np.int64(457),
 np.int64(930),
 np.int64(94),
 np.int64(515),
 np.int64(1495),
 np.int64(2356),
 np.int64(677),
 np.int64(2425),
 np.int64(2451),
 np.int64(431),
 np.int64(795),
 np.int64(514),
 np.int64(2307),
 np.int64(1327),
 np.int64(332),
 np.int64(842),
 np.int64(134),
 np.int64(711),
 np.int64(956),
 np.int64(327),
 np.int64(249),
 np.int64(1381),
 np.int64(521),
 np.int64(281),
 np.int64(787),
 np.int64(1577),
 np.int64(1102),
 np.int64(2463),
 np.int64(171),
 np.int64(418),
 np.int64(169),
 np.int64(444),
 np.int64(168),
 np.int64(1017),
 np.int64(182),
 np.int64(93),
 np.int64(20),
 np.int64(792),
 np.int64(105),
 np.int64(126),
 np.int64(1829),
 np.int64(231),
 np.int64(551),
 np.int64(410),
 np.int64(210),
 np.int64(85),
 np.int64(348),
 np.int64(497),
 np.int64(618),
 np.int64(1319),
 np.int64(193),
 np.int64(1138),
 np.int64(1923),
 np.int64(135),
 np.int64(798),
 np.int64(106),
 np.int64(114),
 np.int64(26),
 np.int64(736),
 np.int64(222),
 np.int64(175),
 np.int64(4325),
 np.int64(87),
 np.int64(579),
 np.int64(426),
 np.int64(1578),
 np.int64(459),
 np.int64(1796),
 np.int64(333),
 np.int64(1786),
 np.int64(1339),
 np.int64(1338),
 np.int64(1431),
 np.int64(112),
 np.int64(107),
 np.int64(148),
 np.int64(1018),
 np.int64(74),
 np.int64(1184),
 np.int64(1532),
 np.int64(183),
 np.int64(1055),
 np.int64(532),
 np.int64(893),
 np.int64(2513),
 np.int64(2),
 np.int64(154),
 np.int64(252),
 np.int64(1852),
 np.int64(476),
 np.int64(827),
 np.int64(199),
 np.int64(2095),
 np.int64(3084),
 np.int64(2638),
 np.int64(1588),
 np.int64(43),
 np.int64(1154),
 np.int64(1140),
 np.int64(554),
 np.int64(57),
 np.int64(1026),
 np.int64(659),
 np.int64(516),
 np.int64(540),
 np.int64(435),
 np.int64(197),
 np.int64(1211),
 np.int64(574),
 np.int64(294),
 np.int64(295),
 np.int64(80),
 np.int64(75),
 np.int64(715),
 np.int64(291),
 np.int64(2472),
 np.int64(257),
 np.int64(1695),
 np.int64(2371),
 np.int64(236),
 np.int64(41),
 np.int64(42),
 np.int64(146),
 np.int64(561),
 np.int64(533),
 np.int64(534),
 np.int64(7),
 np.int64(1141),
 np.int64(1294),
 np.int64(237),
 np.int64(100),
 np.int64(323),
 np.int64(1288),
 np.int64(615),
 np.int64(996),
 np.int64(1423),
 np.int64(1975),
 np.int64(151),
 np.int64(484),
 np.int64(458),
 np.int64(392),
 np.int64(1789),
 np.int64(40),
 np.int64(313),
 np.int64(260),
 np.int64(368),
 np.int64(873),
 np.int64(660),
 np.int64(2475),
 np.int64(1634),
 np.int64(71),
 np.int64(206),
 np.int64(286),
 np.int64(503),
 np.int64(258),
 np.int64(1474),
 np.int64(290),
 np.int64(3664),
 np.int64(1573),
 np.int64(117),
 np.int64(278),
 np.int64(2616),
 np.int64(796),
 np.int64(2268),
 np.int64(2526),
 np.int64(2583),
 np.int64(159),
 np.int64(2514),
 np.int64(1640),
 np.int64(1036),
 np.int64(238),
 np.int64(1586),
 np.int64(116),
 np.int64(454),
 np.int64(66),
 np.int64(288),
 np.int64(524),
 np.int64(174),
 np.int64(185),
 np.int64(1418),
 np.int64(1530),
 np.int64(285),
 np.int64(434),
 np.int64(2105),
 np.int64(2922),
 np.int64(700),
 np.int64(378),
 np.int64(716),
 np.int64(73),
 np.int64(1594),
 np.int64(903),
 np.int64(170),
 np.int64(481),
 np.int64(754),
 np.int64(2115),
 np.int64(1157),
 np.int64(889),
 np.int64(852),
 np.int64(786),
 np.int64(196),
 np.int64(1600),
 np.int64(801),
 np.int64(265),
 np.int64(731),
 np.int64(336),
 np.int64(536),
 np.int64(1455),
 np.int64(1090),
 np.int64(571),
 np.int64(269),
 np.int64(201),
 np.int64(624),
 np.int64(978),
 np.int64(138),
 np.int64(191),
 np.int64(678),
 np.int64(108),
 np.int64(1067),
 np.int64(1150),
 np.int64(1108),
 np.int64(213),
 np.int64(384),
 np.int64(84),
 np.int64(2517),
 np.int64(1249),
 np.int64(882),
 np.int64(157),
 np.int64(917),
 np.int64(137),
 np.int64(817),
 np.int64(460),
 np.int64(39),
 np.int64(1178),
 np.int64(642),
 np.int64(10),
 np.int64(1328),
 np.int64(277),
 np.int64(246),
 np.int64(6),
 np.int64(334),
 np.int64(610),
 np.int64(324),
 np.int64(522),
 np.int64(988),
 np.int64(1860),
 np.int64(50),
 np.int64(2760),
 np.int64(1903),
 np.int64(1329),
 np.int64(500),
 np.int64(969),
 np.int64(44),
 np.int64(321),
 np.int64(322),
 np.int64(45),
 np.int64(46),
 np.int64(573),
 np.int64(2536),
 np.int64(2439),
 np.int64(127),
 np.int64(2527),
 np.int64(273),
 np.int64(1369),
 np.int64(68),
 np.int64(69),
 np.int64(1739),
 np.int64(58),
 np.int64(142),
 np.int64(619),
 np.int64(818),
 np.int64(694),
 np.int64(707),
 ...]

In [82]:
url=[final_rating.iloc[idx]['Image_Url']for idx in ids_index]

In [83]:
url

['http://images.amazon.com/images/P/0451524934.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446610038.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446612790.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451203895.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0140143505.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446527785.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451183665.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1558743669.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679772677.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671886665.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446667900.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0670896764.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/140003065X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553278029.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375725784.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553279912.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375702709.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0525945210.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0374270325.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385720106.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/038550120X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/080411918X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345361792.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553571885.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449907481.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440211727.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375703063.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446608955.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345424719.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440498058.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440220394.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679731148.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0684874350.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/042517736X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1573227331.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446519960.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425151867.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385306024.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679446486.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449217264.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671793489.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553268120.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/080410526X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380718332.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679744398.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446364193.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380789035.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553579983.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0684872153.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/068484267X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0849911672.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671027360.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0064472272.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060921145.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451526341.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553296981.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553213148.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553153277.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553213172.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0786817879.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553579606.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/014025448X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/038572179X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553280341.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0670894184.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/067102423X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385722206.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0452269571.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1551668998.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385413041.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671004573.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060934417.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345327853.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0452264464.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425178579.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345445848.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345438329.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425178102.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345413865.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515137111.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440224845.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345441036.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425175405.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440226104.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385511612.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375502238.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446602620.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425184943.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380717018.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553800973.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060929871.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/037570504X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/042516313X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380432811.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0670892963.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/014028009X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0140298479.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553801430.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553280368.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553282476.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1559029838.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553295977.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515130389.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671039725.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446606189.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/044922046X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425158616.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425174271.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0064400557.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/038533334X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/155874262X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1558744150.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/014100018X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385720920.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425182878.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451128370.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425161242.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440211263.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425122123.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0871136791.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375700757.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440514428.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0061099708.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312958129.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385335482.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060987529.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345378490.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671004107.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425155943.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380977788.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553096834.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446609404.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312198493.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380718340.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/055356160X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451161351.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553271636.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440207622.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743460529.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446394521.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515131229.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449134482.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0821759744.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553287397.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553561618.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/034539657X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671670689.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1551666839.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671011375.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425147584.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671027387.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743418131.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/034538184X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671011367.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451188462.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446359750.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451139682.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312263120.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345391055.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060928336.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451177096.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0786889020.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0786881852.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380727293.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0399137734.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440215625.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/055358264X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/074343627X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345460359.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345439104.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0770427758.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446532231.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553582526.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553560247.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553279556.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/039914613X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440122090.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375703055.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375726403.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0812550706.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0373218192.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446527130.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385318073.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743235150.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446604232.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425158632.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425132048.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679429883.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553284789.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671894455.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/051513287X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/8401422345.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312284683.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743237188.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0452283205.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553580221.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440124344.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060938455.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312980159.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553478257.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425145638.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425097722.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553579754.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553582135.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440200563.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1573229725.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440222842.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060958022.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679459626.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/067101420X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0316678104.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0316781010.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345368754.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446613266.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451170385.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312966970.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0070212570.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425154092.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553582747.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312983271.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/031298328X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449219364.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/067164257X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451176464.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/014029628X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0452282152.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0679746048.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0441003257.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743418174.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345298349.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440224829.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440213991.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0441304834.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553564528.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449219461.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440224675.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312265859.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0439064872.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0439139597.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/043935806X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0439136369.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/043936213X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/059035342X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/067155302X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515128554.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440211891.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671032992.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671024248.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743436210.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515132020.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515133302.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425167313.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446603716.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0590313088.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1573228214.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312971346.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440414806.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449702545.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515124893.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/042516098X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312976275.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0375727345.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451197410.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/1573229326.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345388968.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0312201656.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449221512.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060987561.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0060391626.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0553256157.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671888587.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345384350.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0142000205.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743406176.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0688042171.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451204301.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0743418190.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515124214.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451184963.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345384369.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345337662.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385492081.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385486804.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425155404.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0373484003.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0425182908.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0451149513.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0804105820.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0380710722.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449221482.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446604801.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0064403688.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0767905180.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671038184.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0671042572.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515126772.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0385316879.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345370775.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449221504.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0440201926.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515136379.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/051513628X.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0515136530.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0345453816.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0446601241.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449221490.01.LZZZZZZZ.jpg',
 'http://images.amazon.com/images/P/0449910571.01.LZZZZZZZ.jpg',

In [85]:
import pickle
pickle.dump(model,open('artifacts/model.pkl','wb'))
pickle.dump(book_name,open('artifacts/book_name.pkl','wb'))
pickle.dump(final_rating,open('artifacts/final-rating.pkl','wb'))
pickle.dump(book_pivot,open('artifacts/book_pivot.pkl','wb'))

# Testing model

In [88]:
def recommend_book(book_name):
    book_id=np.where(book_pivot.index==book_name)[0][0]
    distance,suggestion=model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)

    for i in range(len(suggestion)):
        books=book_pivot.index[suggestion[i]]
        for j in books:
            if j==book_name:
                print(f"You Searched '{book_name}'\n")
                print(f"The Suggestion books are :\n ")
            else:
                print(j)

In [89]:
book_name="A Civil Action"

recommend_book(book_name)

You Searched 'A Civil Action'

The Suggestion books are :

No Safe Place
Exclusive
Jacob Have I Loved
Long After Midnight
The Cradle Will Fall